version: '3'
volumes:
  postgres_data:
      driver: local
#
services:
  postgres:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
#      networks:
#        - keycloak-network
      network_mode: host
  keycloak:
      volumes:
        - ./startup_scripts:/opt/jboss/startup-scripts
        - ./imports:/opt/jboss/keycloak/imports
        #- ./deployments:/opt/jboss/keycloak/standalone/deployments
        #- ./themes/custom-theme:/opt/jboss/keycloak/themes/custom-theme
      image: jboss/keycloak:15.0.2
      env_file:
        - ./keycloak.env
      environment:
        JAVA_OPTS: "-Djboss.site.name=keycloak"
        DB_VENDOR: POSTGRES
        DB_ADDR: localhost
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
        KEYCLOAK_STATISTICS: all
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - "9090:8080"
        - "10990:9990"
      depends_on:
        - postgres
        - infinispan
      network_mode: host
#      networks:
#        - keycloak-network



#networks:
#  keycloak-network:
#    driver: bridge