server:
  port: 9090

spring:
  datasource:
    username: sa
    #    url: jdbc:h2:${user.dir}/thb
    url: jdbc:h2:mem:testdb


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
#    realmImportFile: realm.json

logging:
  level:
#    org: DEBUG
    org.keycloak: DEBUG
#    org.jboss: DEBUG
    org.infinispan: DEBUG
#    org.springframework: DEBUG
#    org.springframework.boot.autoconfigure.logging: DEBUG
#    org.springframework.context.support: DEBUG
#    org.hibernate: DEBUG
#    org.h2: DEBUG
